#!/usr/bin/env php
<?php

error_reporting(-1);
ini_set('display_errors', 1);
date_default_timezone_set('UTC');

$horne = require_once __DIR__ . '/src/bootstrap.php';

$horne->run(
    getcwd(),
    json_decode(file_get_contents(getcwd() . '/_horne.json'), true)
);
