<?php
<<<EOT
---
{
    "id": "horne-blog-sub-article-list",
    "type": "_script"
}
---
EOT;

usort($vars['articles'], function ($a, $b) {
    $tmp1 = $a->getMetaPayload();
    $tmp2 = $b->getMetaPayload();

    return strcmp(
        $tmp2['date_created'],
        $tmp1['date_created']
    );
});

?>

<ul class="horne-blog-article-list">
<?php foreach ($vars['articles'] as $articleBag) : $article = $articleBag->getMetaPayload(); ?>
    <li>
        <?php  $dt = DateTime::createFromFormat('Y-m-d H:i:s', $article['date_created'], new DateTimeZone('UTC')); ?>
        <time datetime="<?=$api->e($dt->format('Y-m-d'))?>"><?=$api->e($dt->format('j M, Y'))?></time>

        <a href="<?=$api->url($article['id'])?>"><?=$api->e($article['title'])?></a>

        <?php if (isset($article['teaser'])) : ?>
            &mdash; <?=$api->e($article['teaser'])?>
        <?php endif; ?>

    </li>
<?php endforeach; ?>
</ul>
