<?php

usort($vars['articles'], function ($a, $b) {
    $tmp1 = $a->getMetaPayload();
    $tmp2 = $b->getMetaPayload();

    return strcmp(
        $tmp2['date_created'],
        $tmp1['date_created']
    );
});

?>

<ul>
<?php foreach ($vars['articles'] as $articleBag) : $article = $articleBag->getMetaPayload(); ?>
    <li>
        <a href="<?=$this->url($article['id'])?>"><?=$this->e($article['title'])?></a>
        <?=$this->e($this->datef($article['date_created']))?>

        <?php if (isset($article['teaser'])) : ?>
            <p><?=$this->e($article['teaser'])?></p>
        <?php endif; ?>
    </li>
<?php endforeach; ?>
</ul>
