<?php

$m = $vars['meta'];

$title = (isset($m['title'])) ? $m['title'] : '';

$horne = $this;

$getTitleById = function ($id) use ($horne) {
    $meta = $horne->metas->getByid($id);
    $payload = $meta->getMetaPayload();
    $title = (isset($payload['title'])) ? $payload['title'] : 'Untitled';
    return $title;
};

$menuIds = ['index'];

$skip = ['index', 'horne-debug-debug'];

foreach ($this->getMetasByType('page') as $meta) {
    if (!in_array($meta->getId(), $skip)) {
        $menuIds[] = $meta->getId();
    }
}

?><!DOCTYPE html>

<html lang="en">

<head>
    <meta charset="UTF-8" />
    <title><?=$this->e($title)?></title>
    <link href='<?=$this->getPathToRoot()?>/assets/screen.css' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
</head>

<body>

    <div class="horne-system-header">

    <h1><?=$this->e($this->getSetting('system.siteTitle'))?></h1>

    <?php if (count($menuIds) > 0) : ?>
    <ul class="horne-system-navigation">
    <?php foreach ($menuIds as $id) : ?>
        <li><a href="<?=$this->e($this->url($id))?>"><?=$this->e($getTitleById($id))?></a></li>
    <?php endforeach; ?>
    </ul>
    <?php endif; ?>

    </div>

    <?=$vars['content']?>

    <div class="footer">
        <p>
            Page generated at <?=$this->e(date('Y-m-d H:i:s'))?> UTC.
            <a href="http://validator.w3.org/check/referer">Validate</a>
        </p>
    </div>
</body>

</html>
