<?php
/* ---
{
    'type' : '_default',
    'filters' : []
}
--- */

$m = $vars['meta'];

?>

<h1><?=$this->e($m['title'])?></h1>

<?php if ($this->getSetting('blog.showInfoline')) : ?>
<p class="horne-blog-infoline">
Geschrieben

<?php if (
    $this->getSetting('blog.showAuthor')
    && isset($m['author'])
) : ?>
    von <?=$this->e($m['author']);?>
<?php endif; ?>
    am <?=$this->e($this->datef($m['date_created']))?>.

    <?php if (
        $this->getSetting('blog.useTags')
        && isset($m['tags'])
        && count($m['tags']) > 0
    ) : ?>
        Getaggt mit:
        <?php $sep = ''; ?>
        <?php foreach ($m['tags'] as $tag) : ?>
            <?=$sep?><a href="<?=$this->e($this->url('horne-blog-tag-' . $tag))?>"><?=$this->e($tag)?></a>
            <?php $sep = ', '; ?>
        <?php endforeach; ?>
    <?php endif; ?>

</p>
<?php endif; ?>



<?=$vars['content']?>
