<?php

$childNodesToArray = function (DOMElement $e) {
    $tmp = array();

    foreach ($e->childNodes as $node) {
        /* @var $node DOMElement */
        $tmp[$node->nodeName] = $node;
    }

    return $tmp;
};

$doc = new DOMDocument('1.0', 'UTF-8');
$doc->load($this->getSetting('linkblog.dataFile'));

$xpath = new DOMXPath($doc);

$items = array();

foreach ($xpath->query('/rss/channel/item') as $item) {
    $tmp = $childNodesToArray($item);

    if (!array_key_exists('pubDate', $tmp)) {
        $tmp['pubDate'] = 0;
    } else {
        $tmp['pubDate'] = strtotime($tmp['pubDate']->nodeValue);
    }

    $items[] = $tmp;
}

usort($items, function ($a, $b) {
    $ad = $a['pubDate'];
    $bd = $b['pubDate'];

    $d = strcmp($bd, $ad);

    if ($d !== 0) {
        return $d;
    }

    return strcmp($a['title']->nodeValue, $b['title']->nodeValue);
});

$grouped = array();

foreach ($items as $tmp) {
    $date = $tmp['pubDate'];


    $y = (int) date('Y', $date);
    $m = (int) date('m', $date);
    $d = (int) date('d', $date);

    if (!array_key_exists($y, $grouped)) {
        $grouped[$y] = array();
    }

    if (!array_key_exists($m, $grouped[$y])) {
        $grouped[$y][$m] = array();
    }

    if (!array_key_exists($d, $grouped[$y][$m])) {
        $grouped[$y][$m][$d] = array();
    }

    $grouped[$y][$m][$d][] = $tmp;
}

foreach ($grouped as $year => $grouped2) {
    foreach ($grouped2 as $month => $grouped3) {
        foreach ($grouped3 as $day => $entries) {

            $date = mktime(12, 0, 0, $month, $day, $year);

            echo '<p><strong>' . date('l, F j, Y', $date) . '</strong></p>';
            echo '<ul>';
            foreach ($entries as $tmp) {
                $url = $tmp['link']->nodeValue;
                $host = parse_url($url, PHP_URL_HOST);

                echo '<li>' . $this->e($tmp['title']->nodeValue) . ' <a href="' . $this->e($url) . '">' . $this->e($host) . '</a></li>';
            }
            echo '</ul>';
        }
    }
}
