<?php
<<<EOT
---
{
    "id"     : "horne-layout-article",
    "type"   : "layout",
    "layout" : "horne-layout-default"
}
---
EOT;

namespace Horne;

$m = $vars['meta'];

$next = null;
$prev = null;

$metas = $api->getMetasByType('article', array('date_created' => 'DESC'));

$indexOfMyself = 0;

$i = 0;

foreach ($metas as $tmp) {
    if ($tmp->getId() === $m['id']) {
        $indexOfMyself = $i + 1;
        break;
    }
    $i++;
}

if ($i > 0) {
    $prev = $metas[$i - 1];
}

if ($i < count($metas) - 1) {
    $next = $metas[$i + 1];
}

?>

<div class="horne-blog-article">



<?php if ($next !== null || $prev !== null) : ?>

    <div class="cf">

        <div style="float: left;">
            <a href="<?=$api->e($api->url('index'))?>">Home</a> <span style="color: #ddd;">/</span>

            <?php
            $timestamp = strtotime($m['date_created']);
            $month = date('F', $timestamp);
            $year = date('Y', $timestamp)
            ?>

            <a href="<?=$api->e($api->url('horne-blog-archive-index'))?>"><?=$api->e($year)?></a> <span style="color: #ddd;">/</span>
            <a href="<?=$api->e($api->url('horne-blog-archive-index'))?>"><?=$api->e($month)?></a>

        </div>

    <div class="horne-blog-article-nav" style="float: right;">

    <?php if ($prev !== null) : ?>
    <?php $article = $prev->getMetaPayload(); ?>
        <a title="<?=$api->e($article['title'])?>" id="horne-system-navigation-previous" href="<?=$api->url($article['id'])?>"><?="\xE2\x97\x80"?></a>
    <?php else : ?>
        <span class="horne-system-navigation-disabled"><?="\xE2\x97\x80"?></span>
    <?php endif; ?>

    <?php if ($next !== null) : ?>
    <?php $article = $next->getMetaPayload(); ?>
        <a title="<?=$api->e($article['title'])?>" id="horne-system-navigation-next" href="<?=$api->url($article['id'])?>"><?="\xE2\x96\xB6"?></a>
    <?php else : ?>
        <span class="horne-system-navigation-disabled"><?="\xE2\x96\xB6"?></span>
    <?php endif; ?>

    </div>

    <?php if ($api->getSetting('blog.showArticleCounter')) : ?>
        <p style="text-align: center;"><?=$api->e($indexOfMyself)?>/<?=$api->e(count($metas))?></p>
    <?php endif; ?>

    </div>

<?php endif; ?>



<h1><?=$api->e($m['title'])?></h1>

<?php if ($api->getSetting('blog.showInfoline')) : ?>
<p class="horne-blog-infoline">
Written

<?php if (
    $api->getSetting('blog.showAuthor')
    && isset($m['author'])
) : ?>
    by <?=$api->e($m['author']);?>
<?php endif; ?>
    on <?=$api->e($api->datef($m['date_created']))?>.

    <?php if (
        $api->getSetting('blog.useTags')
        && isset($m['tags'])
        && count($m['tags']) > 0
    ) : ?>
        Tags:
        <?php $sep = ''; ?>
        <?php foreach ($m['tags'] as $tag) : ?>
            <?=$sep?><a href="<?=$api->e($api->url('horne-blog-tag-' . $tag))?>"><?=$api->e($tag)?></a>
            <?php $sep = ', '; ?>
        <?php endforeach; ?>
    <?php endif; ?>

</p>
<?php endif; ?>



<?=$vars['content']?>



</div>
