<?php
<<<EOT
---
{
    "id"     : "horne-layout-article",
    "type"   : "layout",
    "layout" : "horne-layout-default"
}
---
EOT;

namespace Horne;

/* @var $this Application */

$m = $vars['meta'];

$next = null;
$prev = null;

$metas = $this->getMetasByType('article', array('date_created' => 'DESC'));

$indexOfMyself = 0;

$i = 0;

foreach ($metas as $tmp) {
    if ($tmp->getId() === $m['id']) {
        $indexOfMyself = $i + 1;
        break;
    }
    $i++;
}

if ($i > 0) {
    $prev = $metas[$i - 1];
}

if ($i < count($metas) - 1) {
    $next = $metas[$i + 1];
}

?>

<div class="horne-blog-article">

<h1><?=$this->e($m['title'])?></h1>

<?php if ($this->getSetting('blog.showInfoline')) : ?>
<p class="horne-blog-infoline">
Written

<?php if (
    $this->getSetting('blog.showAuthor')
    && isset($m['author'])
) : ?>
    by <?=$this->e($m['author']);?>
<?php endif; ?>
    on <?=$this->e($this->datef($m['date_created']))?>.

    <?php if (
        $this->getSetting('blog.useTags')
        && isset($m['tags'])
        && count($m['tags']) > 0
    ) : ?>
        Tags:
        <?php $sep = ''; ?>
        <?php foreach ($m['tags'] as $tag) : ?>
            <?=$sep?><a href="<?=$this->e($this->url('horne-blog-tag-' . $tag))?>"><?=$this->e($tag)?></a>
            <?php $sep = ', '; ?>
        <?php endforeach; ?>
    <?php endif; ?>

</p>
<?php endif; ?>



<?=$vars['content']?>

<?php if ($next !== null || $prev !== null) : ?>

<div class="cf">

<?php if ($prev !== null) : ?>
<?php $article = $prev->getMetaPayload(); ?>
<div style="float: left; width: 45%; text-align: left;">
    <a id="horne-system-navigation-previous" href="<?=$this->url($article['id'])?>">← <?=$this->e($article['title'])?></a>
</div>
<?php endif; ?>

<?php if ($next !== null) : ?>
<?php $article = $next->getMetaPayload(); ?>
<div style="float: right; width: 45%; text-align: right;">
    <a id="horne-system-navigation-next" href="<?=$this->url($article['id'])?>"><?=$this->e($article['title'])?> →</a>
</div>
<?php endif; ?>

</div>

<p style="text-align: center;"><?=$this->e($indexOfMyself)?>/<?=$this->e(count($metas))?></p>

<?php endif; ?>

</div>
