<?php
$blog = $this->getModule('blog');
?>

<h2>Recent entries</h2>

<?php $articles = $this->getMetasByType('article', ['date_created' => 'desc'], 5); ?>

<?php if (count($articles) === 0) : ?>

    <p>No entries.</p>

<?php else : ?>

    <?=$this->render('horne-blog-sub-article-list', ['articles' => $articles])?>

    <p><a href="<?=$this->e($this->url('horne-blog-archive-index'))?>">Archive</a></p>

<?php endif; ?>

<?php if ($this->getSetting('blog.useTags')) : ?>
    <h2>Tags</h2>

    <?php $tags = $blog->getAllTags(); ?>

    <?php if (count($tags) === 0) : ?>
        <p>No tags.</p>
    <?php else : ?>
        <ul>
        <?php foreach ($blog->getAllTags() as $tag => $amount) : ?>
            <li>
                <a href="<?=$this->url('horne-blog-tag-' . $tag)?>"><?=$this->e($tag)?></a>
                <?php if ($amount > 1) : ?>
                (<?=$this->e($amount)?>)
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
        </ul>
    <?php endif; ?>

<?php endif; ?>
