<?php
<<<EOT
---
{
    "id": "horne-blog-index",
    "type": "_script"
}
---
EOT;

$blog = $api->getModule('blog');
?>

<h2>Recent entries</h2>

<?php $articles = $api->getMetasByType('article', array('date_created' => 'desc'), 5); ?>

<?php if (count($articles) === 0) : ?>

    <p>No entries.</p>

<?php else : ?>

    <?=$api->render('horne-blog-sub-article-list', array('articles' => $articles))?>

    <p><a href="<?=$api->e($api->url('horne-blog-archive-index'))?>">Archive</a></p>

<?php endif; ?>

<?php if ($api->getSetting('blog.useTags')) : ?>
    <h2>Tags</h2>

    <?php $tags = $blog->getAllTags(); ?>

    <?php if (count($tags) === 0) : ?>
        <p>No tags.</p>
    <?php else : ?>
        <ul>
        <?php foreach ($blog->getAllTags() as $tag => $amount) : ?>
            <li>
                <a href="<?=$api->url('horne-blog-tag-' . $tag)?>"><?=$api->e($tag)?></a>
                <?php if ($amount > 1) : ?>
                (<?=$api->e($amount)?>)
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
        </ul>
    <?php endif; ?>

<?php endif; ?>
