<?php
<<<EOT
---
{
    "id": "horne-blog-widget-tags",
    "type": "_script"
}
---
EOT;

$blog = $api->getModule('blog');

$vars['amount'] = array_key_exists('amount', $vars)
        ? $vars['amount']
        : 10;
?>

<?php if ($api->getSetting('blog.useTags')) : ?>
    <h2>Popular tags</h2>

    <?php $tags = $blog->getAllTags(); ?>

    <?php if (count($tags) === 0) : ?>
        <p>No tags.</p>
    <?php else : ?>
        <ul>
        <?php $i = 0; ?>
        <?php foreach ($blog->getAllTags() as $tag => $amount) : ?>
            <?php $i++; ?>
            <?php if ($i > $vars['amount']) { break; } ?>
            <li>
                <a href="<?=$api->e($api->url('horne-blog-tag-' . $tag))?>"><?=$api->e($tag)?></a>
                <?php if ($amount > 1) : ?>
                (<?=$api->e($amount)?>)
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
        </ul>
    <?php endif; ?>

<?php endif; ?>
