<?php
<<<EOT
---
{
    "id": "horne-blog-widget-tags",
    "type": "_script"
}
---
EOT;

$blog = $api->getModule('blog');

$vars['amount'] = array_key_exists('amount', $vars)
        ? $vars['amount']
        : 10;
?>

<?php if ($api->getSetting('blog.useTags')) : ?>
<div class="horne-blog-widget-tags cf">
    <h2>Popular tags</h2>

    <?php $tags = $blog->getAllTags(); ?>

    <?php if (count($tags) === 0) : ?>
        <p>No tags.</p>
    <?php else : ?>
        <ul>
        <?php $i = 0; ?>
        <?php foreach ($blog->getAllTags() as $tag => $amount) : ?>
            <?php $i++; ?>
            <?php if (-1 !== $vars['amount'] && $i > $vars['amount']) { break; } ?>

            <?php $amountLine = $amount . ((1 === $amount) ? ' entry' : ' entries'); ?>

            <li>
                <a href="<?=$api->e($api->url('horne-blog-tag-' . $tag))?>"
                   title="<?=$api->e($amountLine)?>"
                ><?=$api->e($tag)?></a>
            </li>
        <?php endforeach; ?>
        </ul>
    <?php endif; ?>
</div>
<?php endif; ?>
