<?php

namespace Horne;

/* ---
{
    "id": "horne-blog-widget-articles",
    "type": "_script"
}
--- */

/**
 * @var Api   $api
 * @var array $vars
 */

$vars['amount'] = isset($vars['amount']) ? $vars['amount'] : 10;
?>

<div class="horne-blog-widget-articles cf">

<h2>Recent entries</h2>

<?php $articles = $api->getMetasByType('article', ['date_created' => 'desc'], $vars['amount']); ?>

<?php if (count($articles) === 0) : ?>

    <p>No entries.</p>

<?php else : ?>

    <?=$api->render('horne-blog-sub-article-list', ['articles' => $articles])?>

<?php endif; ?>

</div>
