<?php
/* ---
{
    "id": "horne-blog-widget-tags",
    "type": "_script"
}
--- */

/**
 * @var \Horne\Api              $api
 * @var \Horne\Module\Blog\Blog $blog
 * @var array                   $vars
 */

$blog = $api->getModule('blog');

$vars['amount'] = isset($vars['amount']) ? $vars['amount'] : 10;
?>

<?php if ($api->getSetting('blog.useTags')) : ?>
<div class="horne-blog-widget-tags cf">
    <h2>Popular tags</h2>

    <?php $tags = $blog->getAllTags(); ?>

    <?php if (count($tags) === 0) : ?>
        <p>No tags.</p>
    <?php else : ?>
        <ul>
        <?php $i = 0; ?>
        <?php foreach ($blog->getAllTags() as $tag => $amount) : ?>
            <?php
            if (strpos($tag, 'dc:') === 0) {
                continue;
            }

            $i++;

            if (-1 !== $vars['amount'] && $i > $vars['amount']) {
                break;
            }
            ?>

            <?php $amountLine = $amount . (($amount === 1) ? ' entry' : ' entries'); ?>

            <li>
                <a href="<?=$api->e($api->url('horne-blog-tag-' . $tag))?>"
                   title="<?=$api->e($amountLine)?>"
                ><?=$api->e($tag)?></a>
            </li>
        <?php endforeach; ?>
        </ul>
    <?php endif; ?>
</div>
<?php endif; ?>
