<?php
<<<EOT
---
{
    "id"   : "horne-layout-default",
    "type" : "layout"
}
---
EOT;

$m = $vars['meta'];

$title = (isset($m['title'])) ? $m['title'] : '';

$bodyClass = '';

if ($m['id'] === 'index') {
    $bodyClass = ' class="index"';
}

?><!DOCTYPE html>

<html lang="en">

<head>
    <meta charset="UTF-8" />
    <title><?=$api->e($title)?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href='<?=$api->getPathToRoot()?>/assets/screen.css' rel='stylesheet' type='text/css'>
    <script src="<?=$api->getPathToRoot()?>/assets/jquery-1.10.2.min.js"></script>
    <script>
/*<![CDATA[*/
$(function () {
    $(document).keydown(function (event) {
        switch (event.which) {
            case 37:
                var $tmp = $('#horne-system-navigation-previous');
                if ($tmp.length > 0) {
                    window.location = $tmp.attr('href');
                }
                break;
            case 39:
                var $tmp = $('#horne-system-navigation-next');
                if ($tmp.length > 0) {
                    window.location = $tmp.attr('href');
                }
                break;
        }
    });
});
/*]]>*/
    </script>
    <?=$api->render('horne-system-html-head')?>
</head>

<body<?=$bodyClass?>>

    <div class="horne-system-header">
    <div class="horne-system-header-inner cf">

        <h1><a href="<?=$api->e($api->url('index'))?>"><?=$api->e($api->getSetting('system.siteTitle'))?></a></h1>

        <?=$api->render('horne-system-html-mainmenu')?>

    </div>
    </div>

    <div class="horne-system-content">

    <?=$vars['content']?>

    </div>


<?php if ($api->getSetting('system.showFooter')) : ?>
    <div class="footer">
        <p>
            Page generated at <?=$api->e(date('Y-m-d H:i:s'))?> UTC.
            <a href="http://validator.w3.org/check/referer">Validate</a>
        </p>
    </div>
<?php endif; ?>

    <?=$api->render('horne-system-html-foot')?>
</body>

</html>
