<?php

$amonths = array(
    1 => 'January', 2 =>'February', 3 => 'March', 4 => 'April', 5 => 'May', 6 =>'June', 7 => 'July',
    8 => 'August', 9 => 'September', 10 => 'October', 11 => 'November', 12 => 'December'
);

$articles = $this->getMetasByType('article');

$grouped = array();

foreach ($articles as $article) {
    $tmp = $article->getMetaPayload();
    $date = $tmp['date_created'];

    $timestamp = strtotime($date);

    $y = date('Y', $timestamp);
    $m = date('n', $timestamp);

    if (!array_key_exists($y, $grouped)) {
        $grouped[$y] = array();
    }

    if (!array_key_exists($m, $grouped[$y])) {
        $grouped[$y][$m] = array();
    }

    $grouped[$y][$m][] = $article;
}

krsort($grouped);

foreach ($grouped as &$months) {
    krsort($months);
}
unset($months);

?>

<div class="horne-blog-archive-index">

<?php if (count($grouped) === 0) : ?>
    <p>No articles.</p>
<?php endif; ?>

<?php foreach ($grouped as $year => $articlesInYear) : ?>
    <?php foreach ($articlesInYear as $month => $articlesInMonth) : ?>
        <h2><?=$this->e($amonths[$month])?> <?=$this->e($year)?></h2>
        <?=$this->render('horne-blog-sub-article-list', ['articles' => $articlesInMonth])?>
    <?php endforeach; ?>
<?php endforeach; ?>

</div>
