<?php

$articles = $this->getMetasByType('article');

$grouped = [];

foreach ($articles as $article) {
    $date = $article->getMetaPayload()['date_created'];

    $timestamp = strtotime($date);

    $y = date('Y', $timestamp);
    $m = date('n', $timestamp);

    if (!array_key_exists($y, $grouped)) {
        $grouped[$y] = [];
    }

    if (!array_key_exists($m, $grouped[$y])) {
        $grouped[$y][$m] = [];
    }

    $grouped[$y][$m][] = $article;
}

krsort($grouped);

foreach ($grouped as &$months) {
    krsort($months);
}
unset($months);

?>

<?php if (count($grouped) === 0) : ?>
    <p>No articles.</p>
<?php endif; ?>

<?php foreach ($grouped as $year => $articlesInYear) : ?>
<h2><?=$this->e($year)?></h2>
    <?php foreach ($articlesInYear as $month => $articlesInMonth) : ?>
        <h3><?=$this->e($month)?></h3>
        <?=$this->render('horne-blog-sub-article-list', ['articles' => $articlesInMonth])?>
    <?php endforeach; ?>
<?php endforeach; ?>
