<?php

$metas = $this->metas->getAll();

usort($metas, function ($a, $b) {
    return strcmp($a->getType(), $b->getType());
});

?>

<h1>Debug info</h1>

<h2>Metas</h2>

<table>
    <tr>
        <th>ID</th>
        <th>Type</th>
        <th>Source path</th>
    </tr>
<?php foreach ($metas as $meta) : ?>
    <?php
    $payload = $meta->getMetaPayload();
    $url = '';
    if ($meta->getType() !== 'layout') {
        $url = $this->url($payload['id']);
    }
    ?>
    <tr>
        <td>
            <?php if ($url !== '') : ?>
                <a href="<?=$this->e($url)?>">
            <?php endif; ?>
            <?=$this->e($payload['id'])?>
            <?php if ($url !== '') : ?>
                </a>
            <?php endif; ?>
        </td>

        <td><?=$this->e($payload['type'])?></td>
        <td><pre>sourcePath: <?=$this->e($meta->getSourcePath())?>

destPath:  <?=$this->e($meta->getDestPath())?>

<?php print_r($payload); ?></pre></td>
    </tr>
<?php endforeach; ?>
</table>
