<?php

$metas = $this->metas->getAll();

usort($metas, function ($a, $b) {
    return strcmp($a->getType(), $b->getType());
});

?>

<h1>Debug info</h1>

<h2>Metas</h2>

<table>
    <tr>
        <th>ID</th>
        <th>Type</th>
    </tr>
<?php foreach ($metas as $meta) : ?>
    <?php $payload = $meta->getMetaPayload(); ?>
    <tr>
        <td><?=$this->e($payload['id'])?></td>
        <td><?=$this->e($payload['type'])?></td>
    </tr>
<?php endforeach; ?>
</table>
