<?php
<<<EOT
---
{
    "id"     : "horne-debug-debug",
    "title"  : "Debug",
    "type"   : "page",
    "layout" : "horne-layout-debug",
    "path"   : "/debug/index.html"
}
---
EOT;

/* @var \Horne\Api $api */

$metas = $api->getAllMetas();

usort($metas, function (\Horne\MetaBag $a, \Horne\MetaBag $b) {
    return strcmp($a->getType(), $b->getType());
});

?>

<h1>Debug info</h1>

<h2>Metas</h2>

<table>
    <tr>
        <th>ID</th>
        <th>Type</th>
        <th>Source path</th>
    </tr>
<?php foreach ($metas as $meta) : ?>
    <?php
    $payload = $meta->getMetaPayload();
    $url = '';
    if ($meta->getType() !== 'layout') {
        $url = $api->url($payload['id']);
    }
    ?>
    <tr>
        <td>
            <?php if ($url !== '') : ?>
                <a href="<?=$api->e($url)?>">
            <?php endif; ?>
            <?=$api->e($payload['id'])?>
            <?php if ($url !== '') : ?>
                </a>
            <?php endif; ?>
        </td>

        <td><?=$api->e($payload['type'])?></td>
        <td><pre>sourcePath: <?=$api->e($meta->getSourcePath())?>

destPath:  <?=$api->e($meta->getDestPath())?>

<?php print_r($payload); ?></pre></td>
    </tr>
<?php endforeach; ?>
</table>
