<?php

namespace Horne;

/* ---
{
    "id"   : "horne-layout-default",
    "type" : "layout"
}
--- */

/**
 * @var Api   $api
 * @var array $vars
 */

$m = $vars['meta'];

$title = isset($m['title']) ? $m['title'] : '';

$bodyClass = '';

if ($m['id'] === 'index') {
    $bodyClass = ' class="index"';
}

?><!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title><?=$api->e($title)?></title>
    <!--<link href='<?=$api->getPathToRoot()?>/assets/screen.css' rel='stylesheet' type='text/css'>-->
    <script src="<?=$api->getPathToRoot()?>/assets/jquery-1.10.2.min.js"></script>
    <script>
        /*<![CDATA[*/
        $(function () {
            $(document).keydown(function (event) {
                switch (event.which) {
                    case 37:
                        var $tmp = $('#horne-system-navigation-previous');
                        if ($tmp.length > 0) {
                            window.location = $tmp.attr('href');
                        }
                        break;
                    case 39:
                        var $tmp = $('#horne-system-navigation-next');
                        if ($tmp.length > 0) {
                            window.location = $tmp.attr('href');
                        }
                        break;
                }
            });
        });
        /*]]>*/
    </script>
    <?=$api->render('horne-system-html-head')?>
</head>


<body<?=$bodyClass?>>

<div class="container">

    <div class="horne-system-header">
    <div class="horne-system-header-inner cf">

        <h1><a href="<?=$api->e($api->url('index'))?>"><?=$api->e($api->getSetting('system.siteTitle'))?></a></h1>

        <?=$api->render('horne-system-html-mainmenu')?>

    </div>
    </div>

    <div class="horne-system-content">

    <?=$vars['content']?>

    </div>


<?php if ($api->getSetting('system.showFooter')) : ?>
    <div class="footer">
        <p>
            Page generated at <?=$api->e(date('Y-m-d H:i:s'))?> UTC.
            <a href="http://validator.w3.org/check/referer">Validate</a>
        </p>
    </div>
<?php endif; ?>

    <?=$api->render('horne-system-html-foot')?>

</div>
</body>

</html>
