<?php
<<<EOT
---
{
    "type"         : "article",
    "layout"       : "horne-layout-article",
    "title"        : "Test",
    "date_created" : "2013-11-15 16:30:00",
    "tags"         : ["test"],
    "author"       : "John Doe"
}
---
EOT
?>

<p>Quisque blandit eget eros et imperdiet. Fusce hendrerit metus nec urna posuere hendrerit. Curabitur scelerisque condimentum hendrerit. Etiam a leo nec eros consequat ornare ut ac augue. Quisque ultricies pharetra lorem eu lobortis. Sed vel faucibus dolor. Nullam volutpat vehicula urna quis feugiat. Proin in euismod mi. Curabitur feugiat ultrices ipsum eget tincidunt. Sed sit amet ante sed magna ultricies porta vel vitae augue. Curabitur pellentesque massa quis iaculis semper. Quisque in lacus ac ligula lobortis pretium. Donec sed blandit quam. Aenean et adipiscing nisi.</p>

<blockquote><p>Mauris lacinia eleifend sodales. Duis sodales sed neque non eleifend. Aenean mollis ut turpis id elementum. Aliquam suscipit laoreet laoreet. Vivamus lacinia ligula non odio suscipit, laoreet porta justo ornare. Sed vel massa blandit, malesuada nisl at, suscipit felis. Nunc erat lorem, tincidunt vel bibendum id, rutrum sit amet felis. Pellentesque quis odio aliquam, tristique turpis id, faucibus augue. Integer interdum facilisis luctus.</p></blockquote>

<p>Curabitur ultrices leo nec ornare fringilla. Fusce ut lectus nibh. Vivamus posuere nibh at tempus vehicula. Morbi facilisis enim non libero malesuada feugiat. In purus diam, aliquet in mollis at, lacinia id quam. Interdum et malesuada fames ac ante ipsum primis in faucibus. Duis massa nunc, pharetra vitae lacinia id, mollis a risus. Aliquam ornare volutpat mi sed adipiscing. Quisque laoreet lacus nulla, vitae bibendum mi scelerisque sed. Nam dapibus, lectus sollicitudin pellentesque venenatis, felis eros commodo velit, ac egestas mi libero nec nisi.</p>

<p>Numbers from 1 to 10:</p>

<ul>
<?php for ($i = 1; $i <= 10; $i++) : ?>
    <li><?=$i?></li>
<?php endfor; ?>
</ul>
